import type { Metadata } from "next";
import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Headers";
import ToggleLanguage from "@/components/utils/ToggleLanguage";
import "../assets/globals.css";
import { ToastContainer } from "react-toastify";
import { jost } from "@/fonts/allFonts";
import OfflineWrapper from "@/components/pages/OfflineWrapper";
export const metadata: Metadata = {
  title: "EduPress Online Courses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${jost.className}`}>
        <OfflineWrapper>
          <ToastContainer />
          <ToggleLanguage>
            <Header />
            {children}

            <Footer />
          </ToggleLanguage>
        </OfflineWrapper>
      </body>
    </html>
  );
}
