
import "../assets/globals.css";
import type { Metadata } from "next";
import { jost } from "@/fonts/allFonts";
import { ThemeProvider } from "next-themes";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Headers";
import ToggleLanguage from "@/components/utils/ToggleLanguage";
import OfflineWrapper from "@/components/pages/OfflineWrapper";
export const metadata: Metadata = {
  title: "EduPress Online Courses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" data-theme="light">
      <body className={`${jost.className}`}>
        <ThemeProvider attribute="data-theme" defaultTheme="light" enableSystem={false}>
          <OfflineWrapper>
            <ToastContainer />
            <ToggleLanguage>
              <Header />
              {children}
              <Footer />
            </ToggleLanguage>
          </OfflineWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
